### ISSUE TITLE
Implement more possibilities for recurring rule (f.e. INTERVAL > 1)

### ISSUE THREAD

**Issue by SimonSimCity** [adobo/agendav#103]
Please improve the parsing and editing of recurring rules for events. Currently the only interval f.e. is 1 ... this way, you can neither edit, nor see or create an event, that's just occurring every 2nd week.

**Comment by adobo** [comment]
Have a look at #4 :tada:

**Comment by SimonSimCity** [comment]
:+1: :smiley:
