### ISSUE TITLE
rrule monthly fails

### ISSUE THREAD

**Issue by ghost** [adobo/agendav#109]
Trying to insert an event on 31st of January and setting it to repeat monthly will lead to strange behavior.
the next event will be rendered on March 3rd and all following will also be on 3rd of each month.
Shouldn't there be no events in months with less than 31 days and on each 31st (that exists) there has to be the recurring event?

**Comment by adobo** [comment]
This is a pretty old issue. iCalcreator does that kind of things, but AgenDAV now users VObject and this should be not an issue anymore.
