### ISSUE TITLE
Google Calendar access

### ISSUE THREAD

**Issue by natsu90** [adobo/agendav#110]
Hi,

Please make it work with Google Calendar.

http://googledevelopers.blogspot.com/2013/06/making-googles-caldav-and-carddav-apis.html

**Comment by adobo** [comment]
I'm afraid that AgenDAV is meant to provide access to a local CalDAV server. Accessing Google Calendars would complicate the code so much. Sorry, this won't be implemented.

**Comment by roedel1** [comment]
The behaviour - however - can be realized by providing the external source through your CalDAV server. Example:  https://wiki.davical.org/index.php/External_Bind
