### ISSUE TITLE
Uppercase Username get's converted to lowercase

### ISSUE THREAD

**Issue by wasmitnetzen** [adobo/agendav#111]
If you use an username which has an uppercase letter in it (e.g. userName), logging in works just fine, but loading calendars fails because the username will be converted to all lowercase letters (e.g. username) when requesting the calendar from the CalDAV server.

**Comment by adobo** [comment]
Current HEAD (and so, AgenDAV 2.0.0) uses `current-user-principal` to get the principal URL, so issues with uppercase letters should be fixed now.
