### ISSUE TITLE
Mention creation of config in docs

### ISSUE THREAD

**Issue by muelli** [adobo/agendav#115]
I followed the docs but I didn't come very far.
I downloaded, unpacked, and tried to dbupdate, but it complains about a configuration file not existing.

It would be good to know which file is missing.

Bonus points if the error message becomes more meaningful and states at least which file it expected to see. Sugar on top if it provides hints as to how to configure the thing.

**Comment by adobo** [comment]
A note was added in 2.0.0-beta1 docs: http://docs.agendav.org/en/2.0.0-beta1/admin/installation/#create-agendav-tables
