### ISSUE TITLE
Error reading calendar list

### ISSUE THREAD

**Issue by ma2thieu** [adobo/agendav#118]
I get this error connecting on a sabredav server : 
Error reading calendar list
Oops. Unexpected errorparsererror

Request :
https://MY_SERVER/index.php/calendar/all?_=1390212344211

Response :
<b>Fatal error</b>: Call to a member function usersWithAccessTo() on a non-object in <b>/home/www/agendav/web/lib/AgenDAV/CalendarChannels/CalendarHomeSet.php</b> on line <b>88</b><br />

**Comment by adobo** [comment]
Were you using HEAD? Sharing code was completely broken.

This should be fixed now.
