### ISSUE TITLE
Calendars of "resource" principal (DAViCal) aren't displayed

### ISSUE THREAD

**Issue by C-Duv** [adobo/agendav#119]
I'm using AgenDAV together with a DAViCal server (using a LDAP server for user authentication) and it works fine.

For some specific needs I've created a resource via DAViCal administration web interface and added some calendars.
I've granted read/write permissions to some users to theses calendars.

Via a CalDAV client such as Mozilla Lightning I can add and use the calendars (URL : http://davicalserver/caldav.php/resource-foo/calendar-bar/, http://davicalserver/caldav.php/resource-foo/calendar-baz/, etc.) using my (LDAP) credentials.
When I log on AgenDAV I can see my calendar, the calendars my co-workers have shared with me but not the calendars belonging to the resource.

By analyzing web server logs I can see the `PROPFIND /principal/` requests: one for me and one per co-workers but none for the "resource-foo" principal.

Are "resource" supported by AgenDAV?

**Comment by adobo** [comment]
AgenDAV does not support adding user-provided URLs. You could try BINDing your resource calendars into your principal path.

This script could be handy: http://dmfs.org/wiki/index.php?title=DAViCal#Sync_shared_resources
