### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by maggick** [adobo/agendav#121]
Hi there,

This may be a stupid/already answered question but here I go:
The last release is dated from 2012. There is a lot of new commit. 
Is there a new release planned or should I just use the sources directly out of github ?

**Comment by np** [comment]
same question here

**Comment by mmoll** [comment]
count me in :1234:

**Comment by adobo** [comment]
Have a look at this mailing list email: https://groups.google.com/forum/#!topic/agendav-general/WqOQujxhWLo

Hope that answers your question :smile:

**Comment by mmoll** [comment]
thanks :100:

**Comment by maggick** [comment]
great !

**Comment by chikamichi** [comment]
Hi,

Any news on that topic? @adobo

**Comment by adobo** [comment]
Hi, still working on it!

**Comment by adobo** [comment]
AgenDAV 2.0.0-beta1 was released today, have a look at it :fireworks:

**Comment by chikamichi** [comment]
:calendar: !

**Comment by maggick** [comment]
Nice job, the new beta version is looking quit good next to the old one.

**Comment by mmoll** [comment]
wonderful news, I updated from 1.2.6 today and it worked as expected, thanks @adobo!
