### ISSUE TITLE
Show week numbers

### ISSUE THREAD

**Issue by renne** [adobo/agendav#122]
Please display week numbers in the calender.

**Comment by silbaer** [comment]
Yes week numbers in month view would be fine.

For the weekly view you can edit the config like this:

    $config['format_title_week'] = "d. MMM [ yyyy]{ '&#8212;' d. MMM yyyy} '(KW' W')'";

The **W** is the trick. It displays the week number. This german config above displays 
 
    15. Jun — 21. Jun 2015 (KW 25)

**Comment by adobo** [comment]
It's available since 2.0.0 (implemented in #179), so I'm closing this one as done.
