### ISSUE TITLE
Save button in Share tab should save the entered parameters

### ISSUE THREAD

**Issue by gadjou** [adobo/agendav#124]
Hi,
I'm a new user and was first very confused with sharing calendar and thought it wasn't workign at all (I spent hours to look at davical and agendav log and configuration files)

What I did: open calendar property shared tab, enter sharing information, then clicked... "save" button (I did not notice the "+" button).
Sharing was then not saved and i did not understand why.

I thing in this case the" save" boutton should add the sharing (like the "+" button does)

**Comment by adobo** [comment]
This is clearly an UX issue.

The sharing interface will be redone for 2.0.0.

**Comment by adobo** [comment]
Shares tab will have the same behaviour as the reminders editor (on 2.0.0-beta1+). In fact it is already implemented, but the backend part is not still finished. This can be marked as done.
