### ISSUE TITLE
Failing to fetch data because of one calendar-entry ...

### ISSUE THREAD

**Issue by SimonSimCity** [adobo/agendav#125]
I lately got the response from a customer, that his calendar is not working anymore. The reason was, as I saw in the server-response, that the variable `$lastix` in the line https://github.com/adobo/agendav/blob/develop/web/lib/iCalcreator/iCalcreator.class.php#L5870 had a value of `-1` ...

Adding a stacktrace, I got it down to the calendar-object, received by the server: In the file `web/application/libraries/Icshelper.php`, the script calls `vcalendar.parse()` sending the following calendar-object:

````
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Apple Inc.//iOS 7.1.2//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:MESZ
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:MEZ
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20140710T200144Z
DTEND;TZID=Europe/Berlin:20140913T210000
DTSTAMP:20140913T160006Z
DTSTART;TZID=Europe/Berlin:20140913T190000
LAST-MODIFIED:20140913T160005Z
LOCATION:Saal
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:Kick-Off-Meeting für alle Mitarbeiter
TRANSP:OPAQUE
UID:D6729FE1-184A-4803-9C24-5C97487E4832
BEGIN:VALARM
ACKNOWLEDGED:20140913T160005Z
ACTION:DISPLAY
DESCRIPTION:AgenDAV
TRIGGER:-PT1H
UID:44FB8045-34DE-441C-8728-94547857F420
X-WR-ALARMUID:44FB8045-34DE-441C-8728-94547857F420
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Erinnerung
TRIGGER:-PT5M
UID:EDAA5E04-29E1-4D1E-9146-1978B88C4194
X-WR-ALARMUID:EDAA5E04-29E1-4D1E-9146-1978B88C4194
END:VALARM
BEGIN:VALARM
ACTION:NONE
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
END:VALARM
END:VEVENT
END:VCALENDAR
````

Please find what's missing here. Maybe that issue has already been fixed in a later version of `iCalcreator`?

I will, myself, take a look at this if I get time later. For now, I've muted the line for now, using the error-control-operator ...

**Comment by adobo** [comment]
As AgenDAV is switching to VObject instead of iCalcreator, this issue can be closed.

**Comment by SimonSimCity** [comment]
@adobo Is there a timeline or any progress on this one? I heard that also quite some time before opening that issue here ...

**Comment by adobo** [comment]
@SimonSimCity sure! Have a look at the `eventparser` branch. I know, it has such an misleading name...
