### ISSUE TITLE
idt2datetime and numeric array elements

### ISSUE THREAD

**Issue by PeterSurda** [adobo/agendav#128]
Hello,

if DTEND or DTSTART only contains a date and no time, the idt2datetime in web/application/libraries/Dates.php screws up. It does contain a check for that situation, but the check assumes that the array elements are missing. In my case, the array elements are present, but they are a 
numeric 0, rather than a string "00". This causes the whole calendar to break as later the code crashes on calling diff on a non-object and the calendar data is not displayed at all. I use a calendar that is imported from facebook (I wget my facebook calendar into the data folder of radicale). I'm not a caldav expert, so maybe it's a bug in facebook's implementation.

The fix I used is to replace the simple concatenation with this:

if ((is_numeric ($v) && $v < 10)
    $str .= sprintf ("%02d", $v);
else
    $str .= $v;

I do not know if it's relevant but I'm using roundcube agendav plugin rather than standalone agendav.

**Comment by adobo** [comment]
AgenDAV will use VObject instead of iCalcreator for 2.0.0, so this will be not an issue anymore.
