### ISSUE TITLE
Agent Dav repeat function issue after patch

### ISSUE THREAD

**Issue by Garbis1** [adobo/agendav#129]
Although the until date is included in the graphics using a repeat, the event that occurs on the until date does not seemed to be registered as an event on the ICS file.

**Comment by Garbis1** [comment]
Do you happen to have a time frame for a fix to this bug? Thanks

**Comment by adobo** [comment]
Develop branch should have this fixed. It would be great if you could try it to confirm it's fixed.

You'll find instructions on setting up a development environment at https://agendav.readthedocs.org/en/develop/development/

**Comment by Garbis1** [comment]
Can you email me a version of Agent Dav that has the fix?


Thanks




Alberto





From: Jorge López Pérez
Sent: ‎Thursday‎, ‎February‎ ‎5‎, ‎2015 ‎2‎:‎58‎ ‎AM
To: adobo/agendav
Cc: Alberto Ovalles





Develop branch should have this fixed. It would be great if you could try it to confirm it's fixed.

You'll find instructions on setting up a development environment at https://agendav.readthedocs.org/en/develop/development/

**Comment by adobo** [comment]
@Garbis1 you can download it from GitHub here: https://github.com/adobo/agendav/archive/develop.zip

Follow the instructions at http://agendav.readthedocs.org/en/develop/development/ to quickly set up a testing environment.

**Comment by adobo** [comment]
@Garbis1 didn't confirm, but this issue seems to be fixed
