### ISSUE TITLE
DB prefix is ignored by dbupdate script

### ISSUE THREAD

**Issue by MarkMaldaba** [adobo/agendav#131]
Hi there,

I just installed Agendav v1.2.6.2 by importing the basic mysql.schema.sql and running the dbupdate script.

Despite setting `$db['default']['dbprefix'] = 'agendav_'` in config/database.php all tables were created without a prefix.  The application failed to run, however, as the prefix was expected.

Two things to fix (in my opinion):
1. Remove the .sql files so the whole installation is done via the dbupdate command-line script.
2. Update the command-line script to use the 'dbprefix' property correctly when setting up tables.

I fixed it by manually renaming the tables after installation, but I expect this will break in my next update.

**Comment by adobo** [comment]
2.0.0 is the new stable release, closing this one.

**Comment by MarkMaldaba** [comment]
@adobo I can see that the dbupdate script was removed, but does this mean the problem was fixed in v2.0, i.e. that the install/update process now works correctly with a prefix set?  Or is some manual modification still required?

**Comment by adobo** [comment]
@MarkMaldaba setting up a dedicated database for AgenDAV is easy (or should be) and completely advisable. I would recommend setting up a dedicated database for any application that requires a DB.

Sorry, but there are no plans of implementing table prefixes support right now.

**Comment by MarkMaldaba** [comment]
@adobo OK - so you're saying that the bug (that the 'dbprefix' setting wasn't being respected in some places) is fixed because the new version no longer has this functionality (i.e. it does not support table prefixes).

Shame, but thanks for clarifying.

**Comment by adobo** [comment]
Well, the bug was never fixed, you're right. AgenDAV 1.x was based on CodeIgniter, which provided table prefix support, although it was not used by the `dbupdate` script.

I should have mentioned that in 1.x docs, my fault.
