### ISSUE TITLE
Calendar settings UI is broken

### ISSUE THREAD

**Issue by janLo** [adobo/agendav#134]
When I try to change the settings of a calendar I get all information in one tab and above the calendar. Also the icons at the buttons are broken. Browser is chrome 41.0.2272.101 (64-bit) on linux.

![agendav1](https://cloud.githubusercontent.com/assets/96146/6860376/9e0f3158-d427-11e4-806c-fba6e8d32993.png)
![agendav2](https://cloud.githubusercontent.com/assets/96146/6860378/a269e414-d427-11e4-83af-3000887088cb.png)

**Comment by janLo** [comment]
Firefox the same.

**Comment by adobo** [comment]
This is caused by #133. Until sharing gets fixed, you can disable calendar sharing to make this work again.
