### ISSUE TITLE
Sharing calendars doesn’t work AgenDAV 1.2.6.2

### ISSUE THREAD

**Issue by VeryTastyTomato** [adobo/agendav#135]
Hello,

I am trying to use AgenDAV because I need to adapt it to do a project. I use Trisquel 7 (derived from Ubuntu) and I use DAViCal as CalDAV web server in version 1.1.1-1. I had some troubles when using both of them, but I managed to finally connect on AgenDAV and I am able to create calendars and events.

The problem is that I can't share calendars. Existing users are shown when typing some characters on the field for sharing calendars, but when I use the + button, a red pop-up appears saying that the _value is invalid, code HTTP = 403_.

I tried to look at documentation and mailing lists to solve it, but solutions proposed don’t work for me. I use the server name rather the IP address on the file **config.php**, with _http_ instead of _https_, but this still doesn’t work. AgenDAV log says that the ACL of the calendar is not modified because of a 403 code error.

I don’t know how to solve this problem, maybe it’s another fix to apply on DAViCal? Indeed, I already have to modify two files of DAViCal in order to be able to create events on AgenDAV. But here I don’t know how to solve it.

I would be very grateful if you can help me with this struggling situation.

**Comment by adobo** [comment]
@VeryTastyTomato you should not need to modify any DAViCal files at all to make AgenDAV work. In fact, AgenDAV is just a CalDAV client, so it doesn't do anything special.

What web server software are you using?

What do your AgenDAV, DAViCal and web server logs say when trying to share a calendar?

**Comment by adobo** [comment]
Closing this old issue. Please, try AgenDAV >= 2.0.0
