### ISSUE TITLE
mindate for end_date and repeat_until defaults to next day

### ISSUE THREAD

**Issue by morfran** [adobo/agendav#137]
Using the origin/develop branch of Agendav (
commit f6975a43ccb72c1f0055716880bad1379d6f8847), I have a problem where whenever I add an event the mindate for the end and repeat until datepickers is set to the next day. So events end up spanning 25 hours by default.

This may be related to the timezone that I'm using (Pacific/Auckland).

I can make it work by removing the mindate setting code, but naively altering it just appears to break things.

diff --git a/web/public/js/app.js b/web/public/js/app.js
index dd3dc7d..2a97c6a 100644
--- a/web/public/js/app.js
+++ b/web/public/js/app.js
@@ -700,9 +700,9 @@ var handle_date_and_time = function handle_date_and_time(whe
   $repeat_until.datepicker();
 
   // First time datepicker is run we need to set minDate on end date
-  set_mindate(data.start,
-      [ $end_date, $repeat_until ]
-      );
+  // set_mindate(data.start,
+      // [ $end_date, $repeat_until ]
+      // );
 
   // All day checkbox
   $(where).on('change', 'input.allday', function() {

**Comment by adobo** [comment]
Hi @morfran , I have tried setting my timezone to Pacific/Auckland, but I haven't been able to reproduce this issue.

Could you provide a step-by-step guide in order to be able to confirm this bug and try your PR (#138)?

Thank you!

**Comment by morfran** [comment]
Hi @adobo, thanks for taking a look at this. Here's some details of what is happening for me around PR (#138).

Setup:

* Calendar server: SabreDAV 3.0.1, default timezone UTC
* AgenDAV application: git version (current HEAD, origin/develop) default timezone Europe/London
* AgenDAV user account: default timezone Pacific/Auckland

Steps to reproduce:

1. Create an event before midday; end date defaults to the same day as start date.
2. Create an event in the afternoon; end date defaults to the day after start date.

Steps to test:

1. Apply the patch.
2. Create an event before midday; end date defaults to the same day as start date.
3. Create an event in the afternoon; end date defaults to the same day as start date.

Morning:

![agendav-new-event-morning](https://cloud.githubusercontent.com/assets/250264/8560042/fc702b94-2567-11e5-9c31-0649d76bc0cf.png)

Afternoon:
![agendav-new-event-afternoon](https://cloud.githubusercontent.com/assets/250264/8560041/fc70269e-2567-11e5-993a-e8207c055890.png)

**Comment by adobo** [comment]
Thank you for the detailed guide and screenshots! I've been able to reproduce it.

The issue is caused by the browser timezone offset, as the conversion from a UTC-based `moment` object to a native `Date` object applies the offset to the original time. Your PR fixes this issue, so I have just merged it :+1:

Thank you again!
