### ISSUE TITLE
Unable to select Dutch team in Transifex

### ISSUE THREAD

**Issue by stevenroose** [adobo/agendav#141]
If I click the Dutch translation page in Transifex (https://www.transifex.com/adobo/agendav/language/nl_NL/) and want to Join Team, I get a list of languages in which Dutch is not present.

This issue prevents me from contributing to the Dutch translations

**Comment by adobo** [comment]
To be honest, my knowledge about Transifex is really limited, but I think you are listed as Dutch translator for AgenDAV:

![seleccion_108](https://cloud.githubusercontent.com/assets/776565/9435099/0f5f94f4-4a45-11e5-966c-83824fb0d1bf.png)

Were you able to finally join the Dutch team?

**Comment by stevenroose** [comment]
Well, I can use the translate module. So I'm not in the team, but that doesnt seem to be required :p

**Comment by stevenroose** [comment]
Another question on translating though, how can I see what the string is used for?

Mostly (quire important for something like agendav), in English month names are capitalized, in Dutch they are not, but they are when used as a title, f.e. in the header of a month view.

Of course, from the English phrase I can't figure that out...

**Comment by adobo** [comment]
I'm afraid you will have to look at the source code and do some _grepping_ for that.

Don't worry too much about it. You can change a translation if you discover later that it doesn't exactly match the context :relieved:

**Comment by stevenroose** [comment]
Well, I won't be using the interface in Dutch myself, I use everything in English, but other users of my setup would. But ok, they will understand it regardless of the capital letter, though.

**Comment by stevenroose** [comment]
All Dutch is done btw, you can merge it.

**Comment by adobo** [comment]
Great! I will synchronize all new translations just before releasing 2.0.0-beta1

Thank you!
