### ISSUE TITLE
[1.x -> 2.x-beta] Migrations namespace not configured

### ISSUE THREAD

**Issue by chikamichi** [adobo/agendav#145]
Hi,

When running the `php bin/agendavcli migrations:migrate` command, I get:

```
[Doctrine\DBAL\Migrations\MigrationException]                                 
  Migrations namespace must be configured in order to use Doctrine migrations.
```

Is there anything specific to edit/set/configure apart from the obvious `db.options` in web/config/settings.php?

**Comment by mmoll** [comment]
Does a `cd` into the `bin` directory and running `agendavcli` from there work better?

**Comment by chikamichi** [comment]
It worked! It could (should?) be reflected in the documentation.

**Comment by mmoll** [comment]
it should, so please reopen this issue for now

**Comment by adobo** [comment]
Nice catch. I have gone even further, and ``agendavcli`` now lies in the root directory, so this should not be an issue anymore (unless you try to run ``agendavcli`` from a subdirectory).
