### ISSUE TITLE
[2.0.0-beta1] Router issues, 500 upon login

### ISSUE THREAD

**Issue by chikamichi** [adobo/agendav#146]
Hi,

After what appeared to be a successful upgrade to the beta, it seems there is an issue with the login middleware, for accessing my domain (agendav.vauguet.fr) redirects to /login, and that ends up as a 500.

I don't have much clue as to why it does so, though.

**Comment by chikamichi** [comment]
I somewhat fixed the error by changing the access rights on var/log and most importantly, var/cache/twig.

**Comment by chikamichi** [comment]
Because I have another 500, I'll simply use that existing issue :)

I now can see the login form, but when submitting, I have the following error:

> [2015-09-06 15:15:33] myapp.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "OPTIONS /": Method Not Allowed (Allow: GET) (uncaught exception) at /home/jd/opt/agendav/web/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 148 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"OPTIONS /\": Method Not Allowed (Allow: GET) at /home/jd/opt/agendav/web/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/EventListener/RouterListener.php:148, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/jd/opt/agendav/web/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php:101)"} []
> [2015-09-06 15:15:33] myapp.CRITICAL: AgenDAV\Exception: Client error response [url] http://agenda.vauguet.fr/ [status code] 405 [reason phrase] Method Not Allowed (uncaught exception) at /home/jd/opt/agendav/web/src/Http/Client.php line 181 {"exception":"[object] (AgenDAV\\Exception(code: 405): Client error response [url] http://agenda.vauguet.fr/ [status code] 405 [reason phrase] Method Not Allowed at /home/jd/opt/agendav/web/src/Http/Client.php:181)"} []

**Comment by adobo** [comment]
I have just added a note about requirements in the Upgrading section, it's a good suggestion!

AgenDAV is throwing an error because the CalDAV server answered with a 405 (Method Not Allowed) to a request. Can you check your CalDAV server logs and/or AgenDAV HTTP debug logs?

**Comment by chikamichi** [comment]
I'm using sabre-katana, but I don't have anything in the error logs there.

**Comment by adobo** [comment]
There should be an ``http-xxx.log`` file if you have the development mode enabled. Can you have a look at it?

**Comment by chikamichi** [comment]
In sabre-katana/data/log or in /var/log/apache2/sabre-katana/ (where I chose to store my `ErrorLog`), I don't see such a file, `http-xxx-.log`. I guess I'm not running the CalDAV server in development. I searched on the sabre-katana project, but couldn't find how to switch from prod to dev. Could you explain me how to do it?

**Comment by adobo** [comment]
I was actually talking about running AgenDAV in development mode :smiley: . Have a look at http://agendav.readthedocs.org/en/2.0.0-beta1/admin/troubleshooting/#development-environment to learn how to enable the development mode.

After enabling it, you should find a new ``http-xxxx.log`` file inside your AgenDAV logs directory (after requesting something from AgenDAV).

**Comment by chikamichi** [comment]
Alright, thank you for the clarification.

I activated the dev mode, and here's what I have.

In the browser itself, when POSTing for login:

> Whoops, looks like something went wrong.

> 1/1
> Exception in Client.php line 181:
> Client error response [url] http://agenda.vauguet.fr/ [status code] 405 [reason phrase] Method Not Allowed
> in Client.php line 181
> at Client->request('OPTIONS', '') in Client.php line 67
> at Client->canAuthenticate() in Authentication.php line 76
> at Authentication->processLogin(object(Request), object(Application)) in Authentication.php line 37
> at Authentication->loginAction(object(Request), object(Application))
> at call_user_func_array(array(object(Authentication), 'loginAction'), array(object(Request), object(Application))) in HttpKernel.php line 145
> at HttpKernel->handleRaw(object(Request), '1') in HttpKernel.php line 66
> at HttpKernel->handle(object(Request), '1', true) in Application.php line 581
> at Application->handle(object(Request)) in Application.php line 558
> at Application->run() in index.php line 38

And [here is the http log file](https://gist.github.com/chikamichi/9d1faecf7cf662be6eec).

**Comment by chikamichi** [comment]
Btw, I wasn't aware of `SetEnvIf` at first, and wasn't sure about the `Remote_addr` attribute you usedat first, so I looked [in the doc](http://httpd.apache.org/docs/2.4/fr/mod/mod_setenvif.html) and decided to use `SetEnvIf HOST agenda.vauguet.fr AGENDAV_ENVIRONMENT=dev`, which actually seems to be more straightforward as a setup in Agendav's documentation itself for it's already referencing `your.agendav.host` in several places.

**Comment by adobo** [comment]
Seems that AgenDAV is trying to contact itself. Did you set [caldav.baseurl](http://docs.agendav.org/en/2.0.0-beta1/admin/configuration/#confval-caldav.baseurl) to your AgenDAV instance URL? That's why you are getting these errors. You should point it to your sabre-katana installation.

Regarding the ``SetEnvInf`` directive, setting the ``AGENDAV_ENVIRONMENT`` depending on the ``Host:`` header doesn't look like a good idea to me, but maybe I didn't get it right. Would you mind to elaborate?

The example on the docs sets the environment variable depending on the source IP, so some users (usually you) use AgenDAV in development/debug mode.

**Comment by chikamichi** [comment]
Haha yes, you nailed it. I overlooked that completely; such a silly mistake.

I'm able to properly request sabre/katana. Now. I have another issue with invalid credentials (even for new accounts), but I'll have a look at it later on. Thank you!

**Comment by adobo** [comment]
Glad to hear the problem is solved :-)

SabreDAV uses digest authentication by default, so you should have a look at [caldav.auth_method](http://docs.agendav.org/en/2.0.0-beta1/admin/configuration/#confval-caldav.authmethod).

**Comment by chikamichi** [comment]
Yes, that's what I have (`digest`). I guess it's something else.
