### ISSUE TITLE
SNI support in 2.0.0

### ISSUE THREAD

**Issue by nineinchnick** [adobo/agendav#147]
I'm trying to setup Agendav with a SabreDAV server on a shared hosting account. After enabling https it fails to login because it fetches wrong certificate from the server by not providing the right server name. I've verified this using `openssl s_client` with and without the `-servername` param.

**Comment by nineinchnick** [comment]
Actually maybe it's a Guzzle issue, looking into it.

**Comment by nineinchnick** [comment]
Nevermind, I got an old version of curl compiled with PHP.

**Comment by adobo** [comment]
Great news, AgenDAV supports SNI out the box :tada:
