### ISSUE TITLE
agendavcli migrations:migrate can't delete principals_pkey index

### ISSUE THREAD

**Issue by Aguay-val** [adobo/agendav#150]
Hi,

I configured my agendav app to use postgresql databse. But, when i try to do "php agendavcli migrations:migrate" i got an error : 

```
Migration 20150809122309 failed during Execution. Error An exception occurred while executing 'DROP INDEX principals_pkey':

SQLSTATE[2BP01]: Dependent objects still exist: 7 ERREUR:  n'a pas pu supprimer index principals_pkey car il est requis par contrainte principals_pkey sur table principals
HINT:  Vous pouvez supprimer contrainte principals_pkey sur table principals à la place.
                           
  [Doctrine\DBAL\Exception\DriverException]                                                                                                                                    
  An exception occurred while executing 'DROP INDEX principals_pkey':                                                                                                          
  SQLSTATE[2BP01]: Dependent objects still exist: 7 ERREUR:  n'a pas pu supprimer index principals_pkey car il est requis par contrainte principals_pkey sur table principals  
  HINT:  Vous pouvez supprimer contrainte principals_pkey sur table principals à la place.                                                                                     
                                   
  [Doctrine\DBAL\Driver\PDOException]                                                                                                                                          
  SQLSTATE[2BP01]: Dependent objects still exist: 7 ERREUR:  n'a pas pu supprimer index principals_pkey car il est requis par contrainte principals_pkey sur table principals  
  HINT:  Vous pouvez supprimer contrainte principals_pkey sur table principals à la place.                                                                                     
           [PDOException]                                                                                                                                                               
  SQLSTATE[2BP01]: Dependent objects still exist: 7 ERREUR:  n'a pas pu supprimer index principals_pkey car il est requis par contrainte principals_pkey sur table principals  
  HINT:  Vous pouvez supprimer contrainte principals_pkey sur table principals à la place.  

```
I try to manually delete the index but nothing seems to work. Any idea ? 

PS : I can translate in english if needed.

**Comment by adobo** [comment]
@Aguay-val were you trying to upgrade from AgenDAV 1.x or is that a clean installation?

Thank you for your translation offer, but I think you are seeing those messages in French because you have your system language set to French :-P

**Comment by Aguay-val** [comment]
In fact it's in french beacause my system is french :D

**Comment by adobo** [comment]
Sorry, I didn't get it, my fault! I thought you were talking about providing translations for AgenDAV for those messages.

Don't worry, my mother tongue is Spanish and I studied French at school, so the messages are clear to me. I will try to reproduce this bug.

**Comment by edwardsharp** [comment]
hello, i am getting this problem with a new installation of agendav-2.0.0-beta1 using postgres. all i had to do was yank  `$principals->setPrimaryKey(['path']);` out of the migration file file in `agendav-2.0.0-beta1/web/src/DB/MigrationsVersion20150804202842.php` and rerun the migrations. 

(maybe there's a better way?)

**Comment by adobo** [comment]
Seems that the last migration, which has a DROP and a CREATE TABLE for the same table, makes some weird things on PgSQL.

Does 53507592e9639c8d18cd685ac19a4a5eebc386fd fix the issue on PostgreSQL? Direct link to the patch: https://github.com/adobo/agendav/commit/53507592e9639c8d18cd685ac19a4a5eebc386fd.diff

**Comment by edwardsharp** [comment]
@adobo well, doesn't seem to fix, because the problem is the call to `dropTable('principals')` doesn't work because the principals_pkey from MigrationsVersion20150804202842.php is creating a constraint. so this primary key index needs to be dropped first. 

HINT: Vous pouvez supprimer contrainte principals_pkey sur table principals à la place.

**Comment by esphen** [comment]
I also faced this while doing a clean install on a docker container. I worked around it by connecting to postgres and doing the migration manually:
```sql
DROP TABLE principals;
CREATE TABLE principals(
url varchar(255) NOT NULL,
displayname varchar(255),
varchar(255)
);
INSERT INTO schema_versions (version) VALUES ('20150809122309');
```

**Comment by adobo** [comment]
@edwardsharp seems that Doctrine gets confused when the `DROP` and the `CREATE TABLE` appear in the same migration file, so the patch splits the operation into two different migration files.

I can't reproduce the issue when using two different migrations (i.e. using the `feature/issue150` branch). @Aguay-val @edwardsharp  could you also check it?

**Comment by Aguay-val** [comment]
i'll try to check it this evening. I was not able to try again yet.

Stay tuned ! :)

**Comment by edwardsharp** [comment]
i was just able to test this on a fresh install, splitting the files worked out great!  i got stuck in a half-migrated state last time i posted, so put back my modification to Version20150804202842.php

thank you!

**Comment by polyzen** [comment]
:+1:

**Comment by adobo** [comment]
Applied the fix to the develop branch. Thank you all!
