### ISSUE TITLE
Error loading events from calendar

### ISSUE THREAD

**Issue by Jorilx** [adobo/agendav#151]
I'm trying to setup Agendav 2.0.0beta to handle calendars on a Davical server. I've created a new principal ("test") on the server and logged into Agendav, but I'm getting get this error

Interface error: Error loading events from calendar /caldav.php/test/calendar/

The calendar is empty, what can I do to investigate the issue?

Here's what I get if I download the calendar directly from Davical:
```
BEGIN:VCALENDAR
PRODID:-//davical.org//NONSGML AWL Calendar//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:test calendar
END:VCALENDAR
```
Ubuntu 14.04 with PHP 5.5.9 under lighttpd 1.4.33. DAViCal version is 1.1.1 (on another host)

**Comment by adobo** [comment]
Answered on the mailing list, so I'm closing this one.
