### ISSUE TITLE
Synology CalDav HTTPS Error

### ISSUE THREAD

**Issue by TerranoLuna** [adobo/agendav#153]
Hi, I have successfully installed Agendav on a NAS Synology (RS8214+) but i have a problem for connection after login.

If i configure HTTP access : $app['caldav.baseurl'] = 'http://caldav.mondomaine.fr:5005/calendars/';
Access is grant and all is up.

If i configure HTTPS access : $app['caldav.baseurl'] = 'https://caldav.mondomaine.fr:5006/calendars/';
Internal Server append with this in log : 

[2015-12-16 10:22:41] myapp.INFO: Matched route "POST_login" (parameters: "_controller": "\AgenDAV\Controller\Authentication::loginAction", "_route": "POST_login") [] []
[2015-12-16 10:22:41] myapp.DEBUG: Starting CSRF check [] []
[2015-12-16 10:22:41] myapp.DEBUG: CSRF provided by user {"id":"lkjihgfedcba","value":"l466SZIQSEwOJzNCuum_8GJWA9NOycnVCUHPBSXtHwE"} []
[2015-12-16 10:22:41] myapp.DEBUG: CSRF token successfully validated [] []
[2015-12-16 10:22:41] myapp.INFO: > POST /agendav/web/public/index.php/login [] []
[2015-12-16 10:22:41] myapp.CRITICAL: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (uncaught exception) at /volume1/web/agendav/web/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 51 {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: unable to get local issuer certificate at /volume1/web/agendav/web/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51, GuzzleHttp\\Ring\\Exception\\RingException(code: 0): cURL error 60: SSL certificate problem: unable to get local issuer certificate at /volume1/web/agendav/web/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127)"} []
[2015-12-16 10:22:41] myapp.INFO: < 500 [] []

Log says that there is a problem with my SSL certificate but it's fully operationnal in fact for all my uses (website, mail, etc...) ...
How can make it functionnal with agendav ?

Thank's for your help.

**Comment by adobo** [comment]
It's clearly an SSL validation issue. Let me ask you two questions in order to debug the issue. Your case will be useful to add some notes about SSL validation to AgenDAV documentation:

* What PHP version are you using?
* Could you paste the output from the following command?: `openssl s_client -connect caldav.mondomaine.fr:5006`. Anonymize your output as much as you want (hostnames, names, etc)

**Comment by TerranoLuna** [comment]
Hi, thank's for your return.

I have updated my certificate on now, the error is no more here.... But... The application say to me "Username or password incorrect"...

Here the informations needed : 
[phpinfo.pdf](https://github.com/adobo/agendav/files/64064/phpinfo.pdf)
[openssl.txt](https://github.com/adobo/agendav/files/64106/openssl.txt)

find log here : 
[2015-12-16.txt](https://github.com/adobo/agendav/files/64119/2015-12-16.txt)
[http-2015-12-16.txt](https://github.com/adobo/agendav/files/64120/http-2015-12-16.txt)

PS : The Multi CA Root from Comodo was not present in my last intermediate certificate, causing the error. Now, i have include all CA Root certificate, and it's good.

**Comment by TerranoLuna** [comment]
Ok, i have made testing.

I use NGINX Proxy to block port access.
So, the following config is now good: $app['caldav.baseurl'] = 'https://caldav.mondomaine.fr:5006/calendars/';
This use directly WebDav port.

Command:
curl -X PROPFIND -u userlogin:userpass -H "Content-Type: text/xml" -H "Depth: 1" --data "<propfind xmlns='DAV:'><prop><calendar-data xmlns='urn:ietf:params:xml:ns:
caldav'/></prop></propfind>" https://caldav.mondomaine.fr:443/calendars

Result:
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav" xmlns:ns0="DAV:">
<D:response xmlns:g0="urn:ietf:params:xml:ns:caldav">
<D:href>/calendars/</D:href>
<D:propstat>
<D:prop>
<g0:calendar-data/>
</D:prop>
<D:status>HTTP/1.1 404 Not Found</D:status>
</D:propstat>
</D:response>
<D:response xmlns:g0="urn:ietf:params:xml:ns:caldav">
<D:href>/calendars/Famille/</D:href>
<D:propstat>
<D:prop>
<g0:calendar-data/>
</D:prop>
<D:status>HTTP/1.1 404 Not Found</D:status>
</D:propstat>
</D:response>
<D:response xmlns:g0="urn:ietf:params:xml:ns:caldav">
<D:href>/calendars/terrano/</D:href>
<D:propstat>
<D:prop>
<g0:calendar-data/>
</D:prop>
<D:status>HTTP/1.1 404 Not Found</D:status>
</D:propstat>
</D:response>
<D:response xmlns:g0="urn:ietf:params:xml:ns:caldav">
<D:href>/calendars/Poubelles/</D:href>
<D:propstat>
<D:prop>
<g0:calendar-data/>
</D:prop>
<D:status>HTTP/1.1 404 Not Found</D:status>
</D:propstat>
</D:response>
<D:response xmlns:g0="urn:ietf:params:xml:ns:caldav">
<D:href>/calendars/wild/</D:href>
<D:propstat>
<D:prop>
<g0:calendar-data/>
</D:prop>
<D:status>HTTP/1.1 404 Not Found</D:status>
</D:propstat>
</D:response>
</D:multistatus>

PS: <D:status>HTTP/1.1 404 Not Found</D:status> is very strange....



But, the following is not good: $app['caldav.baseurl'] = 'https://caldav.mondomaine.fr:443/calendars/';
Indeed, this use NGINX to redirect request to localhost:5006. But, NGINX seems to block CalDAV command... :(

Command:
curl -X PROPFIND -u userlogin:userpass -H "Content-Type: text/xml" -H "Depth: 1" --data "<propfind xmlns='DAV:'><prop><calendar-data xmlns='urn:ietf:params:xml:ns:
caldav'/></prop></propfind>" https://caldav.mondomaine.fr:443/calendars

Result:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method PROPFIND is not allowed for the URL /calendars.</p>
</body></html>

**Comment by adobo** [comment]
Are https connection issues fixed after configuring the right intermediate CA chain?

In case they are, please, file a different issue to try not to mix topics, and close this one. Thank you!
