### ISSUE TITLE
Synology CalDav Calendar Reminder not loaded

### ISSUE THREAD

**Issue by TerranoLuna** [adobo/agendav#155]
I can add new event, add reminder (and viewing reminder on Apple Device) but when i reload event under Agendav, no reminders appears.

If i try to add another reminder, this not work (no reminder added or defined reminder not change).

**Comment by adobo** [comment]
An http debug log would help a lot on this issue too

**Comment by TerranoLuna** [comment]
Here log generate with the following steps:
- Creating new event Test Reminder with a reminder of 30 minutes
- editing event : no reminder appear
- adding new reminder of 60 minutes
- Saving
- editing event : no reminder appear
- adding new reminder of 15 minutes
- Saving

[2015-12-17.txt](https://github.com/adobo/agendav/files/65339/2015-12-17.txt)
[http-2015-12-17.txt](https://github.com/adobo/agendav/files/65340/http-2015-12-17.txt)

**Comment by adobo** [comment]
Looks like the Synology CalDAV server is ignoring all VALARM components. They appear on AgenDAV requests when creating/updating events, but are not returned when requesting them back from the server.

I'm afraid AgenDAV can't do anything about this.
