### ISSUE TITLE
icalendar version

### ISSUE THREAD

**Issue by anedisi** [adobo/agendav#159]
I tried to create event on apple caldav server.

VObjectHelper@setBaseVEvent

is defined as 

    public static function setBaseVEvent(VCalendar $vcalendar, VEvent $base)
    {
        $position = 0;

        foreach ($vcalendar->select('VEVENT') as $i => $vevent) {
            if (!isset($vevent->{'RECURRENCE-ID'})) {
                $position = $i;
                break;
            }
        }

        $vcalendar->children[$position] = $base;
    }

it strips the VCALENDAR of the version because it sets the cildren at position 0,
changing it to position 1 fixes the problem, but im not sure is that the correct way to fix this.

According to 
https://tools.ietf.org/html/rfc5545#page-80
This property MUST be specified once in an iCalendar object.

Also, do you have and recommended resources for caldav i tried to get this to work with google and apple caldav servers and im finding inconsistencies. i would like to skip reading the rfcs if i could.

Thank you.

**Comment by adobo** [comment]
@anedisi can you provide an example? It would be helpful to fix the issue and also to write a new test.

**Comment by anedisi** [comment]
Ok, here is the default request.

    BEGIN:VCALENDAR
    PRODID:-//Sabre//Sabre VObject 3.5.0//EN
    CALSCALE:GREGORIAN
    BEGIN:VEVENT
    UID:254fcc43-e64c-4861-8f42-6ecc50009b91
    DTSTAMP:20160212T094931Z
    SUMMARY:Work Work Work
    CLASS:PUBLIC
    TRANSP:OPAQUE
    DTSTART;TZID=Europe/Madrid:20160212T084500
    DTEND;TZID=Europe/Madrid:20160212T094500
    CREATED:20160212T094931Z
    LAST-MODIFIED:20160212T094931Z
    SEQUENCE:0
    END:VEVENT
    END:VCALENDAR

And here is the response.

    <?xml version='1.0' encoding='UTF-8'?><error xmlns='DAV:'><valid-calendar-data xmlns='urn:ietf:params:xml:ns:caldav'/><error-description xmlns='urn:mobileme:davservices'>Invalid calendar data: Not a version 2.0 iCalendar (version=None)</error-description></error>

and this with the "fix"

    BEGIN:VCALENDAR
    VERSION:2.0
    CALSCALE:GREGORIAN
    BEGIN:VEVENT
    UID:bb711e74-60a0-40c6-8634-2a8fa68be67f
    DTSTAMP:20160212T094957Z
    SUMMARY:Work Work Work
    CLASS:PUBLIC
    TRANSP:OPAQUE
    DTSTART;TZID=Europe/Madrid:20160212T084500
    DTEND;TZID=Europe/Madrid:20160212T094500
    CREATED:20160212T094957Z
    LAST-MODIFIED:20160212T094957Z
    SEQUENCE:0
    END:VEVENT
    END:VCALENDAR

**Comment by anedisi** [comment]
i have overwritten some other properties now, but could the starting position be the last child +1 ?

**Comment by adobo** [comment]
This should be fixed on last commit. Thank you for reporting it!
