### ISSUE TITLE
Class "AgenDAV\Data\Preferences" is not a valid entity or mapped super class.

### ISSUE THREAD

**Issue by polyzen** [adobo/agendav#160]
After attempting to login, I receive an "Internal server error":
myapp.CRITICAL: Doctrine\ORM\Mapping\MappingException: Class "AgenDAV\Data\Preferences" is not a valid entity or mapped super class. (uncaught exception) at <redacted>/web/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 346 {"exception":"[object] (Doctrine\\ORM\\Mapping\\MappingException(code: 0): Class \"AgenDAV\\Data\\Preferences\" is not a valid entity or mapped super class. at <redacted>/web
/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:346)"}

```
agendav=# \dt
              List of relations
 Schema |      Name       | Type  |  Owner   
--------+-----------------+-------+----------
 public | prefs           | table | agendav
 public | principals      | table | postgres
 public | schema_versions | table | agendav
 public | sessions        | table | agendav
 public | shares          | table | agendav
```

Edit: 2.0.0-beta1 fresh install
Edit2: [Output from dev environment](https://ptpb.pw/Ks1v)

**Comment by adobo** [comment]
@polyzen can you give us more details about your environment?

**Comment by polyzen** [comment]
Certainly, Jorge. php 7.0.3 & postgresql 9.4.5 on Arch Linux Arm

On Sun, Feb 21, 2016 at 1:00 PM, Jorge López Pérez <notifications@github.com

**Comment by adobo** [comment]
Does it happen on latest HEAD too? I have tried it with PHP 7.0.3 under Ubuntu with no issues (on the AgenDAV side, I had to upgrade Baïkal to make it work).

I don't know if has to do with the architecture (ARM vs x86_64), let me know if latest HEAD has this problem too.

**Comment by polyzen** [comment]
Thank you. I will do that.

On Thu, Feb 25, 2016 at 1:31 PM, Jorge López Pérez <notifications@github.com

**Comment by polyzen** [comment]
There was a different issue when I had tried to install agendav with symlinks (prior to this issue). That same issue occurred when trying to use master (no symlinking or anything).

I will re-open this when I have time to try the latest HEAD and look into this more.

Thank you.
