### ISSUE TITLE
Cannot redeclare class CI_Session

### ISSUE THREAD

**Issue by z000ao8q** [adobo/agendav#161]
I setup the current 1.2.6.2
Configtest shows all in green.

agendav/web/public/index.php
gives a blank screen; 
nginx **error.log** shows
`PHP message: PHP Fatal error:  Cannot redeclare class CI_Session in /var/www/agendav/web/application/libraries/Session.php on line 3`

enabling "define('ENVIRONMENT', '**development**');" gives:
 `Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257`
`Severity: Notice
Message: Undefined index: subclass_prefix
Filename: core/CodeIgniter.php
Line Number: 237`
`Fatal error: Cannot redeclare class CI_Session in /var/www/agendav/web/application/libraries/Session.php on line 3`

**config.php**
`<?php
$config['base_url'] = 'https://jessie-test/agendav/';
$config['show_in_log']= array('ERROR','INFO','AUTHERR', 'AUTHOK', 'INTERNALS');
$config['log_path'] = '/var/log/agendav/';`

any help is apreciated

**Comment by z000ao8q** [comment]
I installed the 2.0 and it worked right away

**Comment by adobo** [comment]
@z000ao8q looks like a PHP compatibility issue. What PHP version were you using?
