### ISSUE TITLE
Require PHP 5.5 or greater for AgenDAV 2.0.0

### ISSUE THREAD

**Issue by adobo** [adobo/agendav#165]
Requiring PHP 5.4 makes no sense on 2016 for a project like AgenDAV. PHP 5.5 seems like a sensible choice.

Let's talk about what we can do after raising the minimum PHP requirement to 5.5, mainly:

- What packages were being held because of PHP 5.4 compatibility
- What packages could benefit from upgrading to a more modern release

**Comment by mmoll** [comment]
I guess the real need for now would be an update of `sabre/dav` to 3.x, as 2.x will not be maintained after June 2016: http://sabre.io/dav/upgrading/ - However, 3.0.x would still be PHP 5.4 compatiable.

**Comment by adobo** [comment]
@mmoll AgenDAV now uses sabre/dav 3.1.3 and sabre/vobject 4.1.0.

Would you mind doing some testing before closing this issue? I plan to release it as beta2 in the next days :tada:

**Comment by mmoll** [comment]
@adobo For beta2, it would be nice to pull in the last synfony patch level with #169 - I am deploying that state on my instance now, if you don't hear back in this issue in the next days, everything is running fine.

**Comment by mmoll** [comment]
@adobo BTW, I think you might need to pull new translations from transifex (or is that part of some release job you're running then?).

**Comment by adobo** [comment]
I usually do it just before preparing a new release, don't worry, it's in my TODO list :+1:

**Comment by adobo** [comment]
Just released 2.0.0-beta2. Thank you for your suggestions!
