### ISSUE TITLE
jssettings Internal Server Error

### ISSUE THREAD

**Issue by ItsMeooooooo** [adobo/agendav#166]
I run the 2.0.0-beta1 version. But on one Server I get an Internal Server Error when loading 'jssettings'
The server log shows: "GET /jssettings HTTP/1.1" 500 854 "-"
The server runs on PHP 5.6.19

As a Result, when I login I can't see any calendar.

**Comment by adobo** [comment]
What do your web server error log and AgenDAV log say?

**Comment by ItsMeooooooo** [comment]
nginx access log:
`"GET /jssettings HTTP/1.1" 500 854 "https://foo.bar.com/" `

nginx error log:
`in /var/www/html/calendar/web/vendor/monolog/monolog/src/Monolog/Logger.php on line 272" while reading response header from upstream, client: x.x.x.x, server: calendar.yave.me, request: "GET /jssettings HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/foo.bar.com:", host: "foo.bar.com", referrer: "https://foo.bar.com/"`

Agendav log:
`myapp.CRITICAL: Exception: DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (uncaught exception) at /var/www/html/calendar/web/src/Controller/JavaScriptCode.php line 51 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. at /var/www/html/calendar/web/src/Controller/JavaScriptCode.php:51)"} []
`

**Comment by adobo** [comment]
The exception message gives a useful hint:

>  You are *required* to use the date.timezone setting

Seems like you don't have a `date.timezone` setting inside your `php.ini`.

BTW I'm going to update the documentation to include a reference to `date.timezone`.
