### ISSUE TITLE
Editing all instances of a recurrent event renders an extra event

### ISSUE THREAD

**Issue by adobo** [adobo/agendav#170]
When expanding a recurrent event, vobject 4.1.0 adds a `RECURRENCE-ID` even for the first instance, so our method to check if we are rendering the first event on a sequence (`recurrence-id === null`) isn't working.

As a side effect, when using the _Edit all repetitions_ on a recurrent event, a bogus event gets rendered on the calendar. It is generated by the `load_base_event_for()` function.

**Comment by evert** [comment]
This is an interesting bug, and similar to bugs I've run into. Adding the `RECURRENCE-ID` made me think a bit different about the actual recurrence data model. The 'first' instance in the recurrence is basically no longer special. It can be overridden like any of the others.

**Comment by adobo** [comment]
While trying to implement a fix for this, your comment made me think.

I was treating the first instance as an special case from which I could extract the base event details, but I was clearly wrong about that.

Time to think about a new approach!
