### ISSUE TITLE
Interface error: error loadinf events from calendar ...

### ISSUE THREAD

**Issue by lumsgoy** [adobo/agendav#171]
I have a just installed AgenDAV on my server, running with Baïkal. Very nice tool, I can see calendars, create calendars, create events, ... However AgenDAV cannot show the events and throws the following error:
`Interface error: error loadinf events from calendar ...`
on the browser interface. I have no such problems with Lightning in Thunderbird, for the same calendar. I have activated the dev mode and looked at the logs, along with the fastcgi logs from nginx, but I cannot see any errors. Do you have any ideas ?

**Comment by adobo** [comment]
Hi @lumsgoy, what AgenDAV version are you using? I assume you are on 2.0.0*.

Can you double check your AgenDAV, php-fpm and nginx error logs when in development mode? They should say something about the error.

**Comment by omg1976** [comment]
Hi @adobo and @lumsgoy, I think I have the same problem

I was using agendav without problems with a ubuntu server 14.04. I have upgraded the server to 16.04 version. I think the main change is PHP, that moved from version 5 to 7.
Now, when I enter my agendav site, the calendar events don't shows and the "Interface error" appears.

This is my log with development mode active:
[log.txt](https://github.com/adobo/agendav/files/244374/log.txt)

**Comment by omg1976** [comment]
Forget everything... the failure was in baikal server (version 0.2.7 must have some problem with PHP7). Current baikal 0.4.4 works fine again.

**Comment by lumsgoy** [comment]
Dear @adobo, I'm much sorry for the late reply. I indeed use AgenDAV 2.0.0 ... and Baïkal 0.2.7. I'll try Baïkal 0.4.4 right away, thanks for the tip @osmogar !

**Comment by lumsgoy** [comment]
Sadly, I still get the same issue :(

The only error I seem to get is in the http log:

[agendav_settings.txt](https://github.com/adobo/agendav/files/288480/agendav_settings.txt)
[agendav_log.txt](https://github.com/adobo/agendav/files/288488/agendav_log.txt)

**Comment by osmogar** [comment]
By default, baikal authentication is digest... have you changed it to basic? (In your agendav settings it is set to basic)

**Comment by lumsgoy** [comment]
I changed it to "basic" indeed, so that it works with davdroid (dav client for android).

**Comment by osmogar** [comment]
The only significant change between my config and yours is:
`$app['caldav.baseurl'] = 'https://baikal.mysite/cal.php/calendars/';`

I have only one user and my baseurl looks like:
`$app['caldav.baseurl'] = 'https://baikal.mysite/cal.php/calendars/user/';`

**Comment by lumsgoy** [comment]
Thanks for the tip. I tried adding my username to the address, but it acts the same as before. AgenDAV is still unable to display my events. 

Interesting thing is, the events I create with AgenDAV are correctly created and appear on all my other CalDAV clients. So it seems like the CalDAV communication is working.

Do you use AgendDAV behind Nginx ? If yes, here's my config file for Nginx, 
[agendav_nginx.txt](https://github.com/adobo/agendav/files/289253/agendav_nginx.txt)

**Comment by adobo** [comment]
The HTTP debug log doesn't show any REPORTs, so perhaps this is an issue while building calendar URLs.

Can you try setting `caldav.baseurl` to `https://baikal.mysite/cal.php` to see if it helps?

**Comment by lumsgoy** [comment]
I set the address to `https://baikal.mysite/cal.ph`, I still get the same error, here's the http log:
[agendav_httplog2.txt](https://github.com/adobo/agendav/files/289444/agendav_httplog2.txt)
and the other log:
[agendav_log2.txt](https://github.com/adobo/agendav/files/289447/agendav_log2.txt)

**Comment by adobo** [comment]
What happens if you open in your browser any of the events URL, such as `/events?calendar=%2Fcal.php%2Fcalendars%2Fachilletalon%2Fdefault%2F&start=2016-04-25&end=2016-06-06&timezone=Europe%2FMadrid&_=1464615192955` ?

After inspecting your debug log, I suspect you are getting an _Invalid input_ exception, let's confirm it.

**Comment by lumsgoy** [comment]
Dear @adobo , when I set the URL to
`https://baikal.mysite/cal.php/calendars/achilletalon/default/events?calendar=%2Fcal.php%2Fcalendars%2Fachilletalon%2Fdefault%2F&start=2016-04-25&end=2016-06-06&timezone=Europe%2FMadrid&_=1464615192955%20?`, I get the following error:
```XML
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Calendar object not found</s:message>
```

**Comment by adobo** [comment]
Sorry, I wasn't clear enough on my last comment. I meant accessing to `https://agendav.mysite/events?calendar=%2Fcal.php%2Fcalendars%2Fachilletalon%2Fdefault%2F&start=2016-04-25&end=2016-06-06&timezone=Europe%2FMadrid&_=1464615192955`

**Comment by lumsgoy** [comment]
My bad, I get the following error
` {"result":"EXCEPTION","message":"Invalid value"}`

**Comment by adobo** [comment]
@lumsgoy I suspect your nginx configuration isn't working as expected.

After looking at your nginx configuration, seems that you are not following the template at: http://silex.sensiolabs.org/doc/master/web_servers.html#nginx . Would you mind to replace your configuration with that one?

**Comment by lumsgoy** [comment]
Aye, indeed. Works like a charm now! I have now all events shown for all my calendars. Thanks a million !

**Comment by adobo** [comment]
Glad to read that!

**Comment by taylor87654321** [comment]
Does anybody have a copy of the correct nginx config file? The link provided doesn't work anymore and I am getting the same error with my nginx server. Thanks in advance for any help! I am super excited to get Agendav working!
