### ISSUE TITLE
Is there any interest in google/apple clients ?

### ISSUE THREAD

**Issue by anedisi** [adobo/agendav#172]
The client as it is now is not really compatible with google/apple caldav servers.
Is there any interest in implementing a client for google and apple servers ?
I have a "hacked" soultion now".

I know that icloud and google have a web client so the interest is maybe limited ?

**Comment by adobo** [comment]
Google calendar and Apple iCloud will always work better with their own clients, as they only need to be compatible with one service. They may use custom internal protocols and a public facing CalDAV frontend with no 1:1 correspondence, so it's not strange that using a CalDAV client produces unexpected behaviours.

Perhaps you found one or more bugs that could affect some CalDAV servers. Would you mind to describe what you found?

**Comment by adobo** [comment]
Closing this issue due to inactivty.
