### ISSUE TITLE
What is needed to release 2.0.0?

### ISSUE THREAD

**Issue by rsertelon** [adobo/agendav#173]
Hi,

I'm using version 1.x of AgenDAV and find it useful. I've just seen that there's a 2.0.0-beta2 released, do you need particular help to get 2.0.0 out?

**Comment by polyzen** [comment]
http://docs.agendav.org/en/2.0.0-beta2/admin/

**Comment by rsertelon** [comment]
@polyzen What am I to do with the 2.0.0-beta2 doc?

I can't see a page that would answer my question ;)

**Comment by polyzen** [comment]
Sorry I misunderstood. :)

**Comment by adobo** [comment]
AgenDAV 2.0.0-beta2 is completely functional, but calendar sharing is not ready yet. Some organizations use it on AgenDAV 1.x, so I can't release 2.0.0 without this feature.

I'm working on it!

**Comment by rsertelon** [comment]
Great, I'll upgrade it to 2.0.0-beta2 on my server then, thanks a lot for your answer ;)
