### ISSUE TITLE
domain URL redirected to ./login

### ISSUE THREAD

**Issue by gadjou** [adobo/agendav#175]
agenDAV 2.0.0-beta2 on Debian 8.4 stable (Jessie) 
davical 1.1.1 on Ubuntu Server 14.04

Hello
After migrating from agenDAV 1.2.6.2 to 2.0.0 every time I browse to my server address directly https://calendar.DOMAIN.eu, I'm redirected to https://calendar.DOMAIN.eu/login, with lead to "not found" error.
If I browse https://calendar.DOMAIN.eu/index.php instead, I'm able to login an see my calendars.

Apache virtual host seems ok. I cleaned cache, cookies and tried IE, ff and chrome with the same result.

How to prevent the redirection? Thanks

**Comment by adobo** [comment]
Looks like an Apache rewrite issue. `/login` should work.

Did you use the configuration suggested at http://docs.agendav.org/en/2.0.0-beta2/admin/installation/#configuring-apache-to-serve-agendav ?

**Comment by gadjou** [comment]
I did. Actually, I force https redirection. Here is my apache conf:
`<IfModule mod_ssl.c>
        <VirtualHost *:80>
                ServerName      calendar.MYDOMAIN
                Redirect        / https://calendar.MYDOMAIN
        </VirtualHost>

        <VirtualHost _default_:443>
                ServerAdmin admin@MYDOMAIN

                ServerName calendar.MYDOMAIN

                DocumentRoot /var/www/agendav/web/public

               ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLProtocol all -SSLv2
    SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM

    SSLCertificateFile       /etc/ssl/certs/calendar.MYDOMAIN.crt
    SSLCertificateKeyFile    /etc/ssl/private/calendar.MYDOMAIN.key
    SSLCertificateChainFile  /etc/ssl/chains/sub.class1.server.ca.pem
    SSLCACertificateFile     /etc/ssl/roots/ca.pem
        CustomLog ${APACHE_LOG_DIR}/ssl_request_log \
      "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>

                BrowserMatch "MSIE [2-6]" \
                                nokeepalive ssl-unclean-shutdown \
                                downgrade-1.0 force-response-1.0
                # MSIE 7 and newer should be able to use keepalive
                BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

        </VirtualHost>
</IfModule>`

**Comment by adobo** [comment]
I can't see any rewrite rules there, and that explains why AgenDAV URLs are not working for you. This part is really important (taken from the installation link from my last comment):

```
 <Location />
   RewriteEngine On
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteRule ^ index.php [QSA,L]
 </Location>
```

**Comment by gadjou** [comment]
I missed it. It solves my problem. Thank you very much for your help.

**Comment by adobo** [comment]
Glad to hear that!
