### ISSUE TITLE
AgenDAV 1.2.6.2 does not show any events from Baikal CalDAV server

### ISSUE THREAD

**Issue by hamiltonian** [adobo/agendav#177]
Hi,

I have a Baikal (https://github.com/fruux/Baikal) Calendar/Contact Server up and running for a while which can be accessed via Thunderbird, Android and Windows Phone quite well.
Now, I tried to set up AgenDAV in order to have a web client as well. I am able to log in to the AgenDAV client and I can see the calendars associated to the account I use. I am also able to create new events which appear in my calendar, however I am not able to see any calendar entries. The log file shows me a lot of messages like this:

```
ERROR - 2016-07-29 14:02:07 --> user@ip-from-login-pc Couldn't parse event with href=user:default/6b295022-0f44-466a-9d5f-26262cf63e3c.ics [event/all]
ERROR - 2016-07-29 14:02:07 --> user@ip-from-login-pc Server sent an event which doesn't fit in our dates interval [event/all]
```

Is there any clue which might help to get this working?

Best regards and thanks in advance,

Hamiltonian

**Comment by SamGoody** [comment]
Same issue here, using Sabre/DAV (not sure what the difference is between it and Baikal).

Details:  
- Agendav Version: 2.0.0-b2  
- Server: Ubuntu 16.04.1 Xenial  
- Web server: Nginx 1.11.3  
- CalDAV server: Sabre/DAV 3.2  

Am able to connect to Sabre/DAV with Apple Calendar and Thunderbird + Lightnining. When I attempt to connect using AgenDAV, it displays the calendar with no events.

As suggested in issue #171, am using the nginx configuration from  http://silex.sensiolabs.org/doc/master/web_servers.html#nginx

I am using digest on Sabre/DAV, and have changed the auth type to "digest" in AgenDAV.

It should be noted that debugging showed a probably unrelated issue. I was getting a fatal error error, and based on https://github.com/symfony/symfony/issues/18651, I added the line to config/app/controllers.php: `use Symfony\Component\HttpFoundation\Request;`  

The error I am getting is from the page:
https://example.com/events?calendar=%2Fcalendars%2Fadmin%2Fdefault%2F&start=2016-07-31&end=2016-09-04&timezone=Europe%2FMadrid&_=1471367959721 
Which responds with {"result":"ERROR","message":"Received unexpected HTTP code 500 from server"}

Am using debug mode, and the error log shows:

```
HTTP/1.1 500 Internal Server Error^M
Server: nginx/1.11.3^M
Date: Tue, 16 Aug 2016 17:37:11 GMT^M
Content-Type: application/xml; charset=utf-8^M
Transfer-Encoding: chunked^M
Connection: keep-alive^M
X-Sabre-Version: 3.2.0^M
^M
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.0</s:sabredav-version>
  <s:exception>ErrorException</s:exception>
  <s:message>XMLReader::XML(): Empty string supplied as input</s:message>
</d:error>

~~~~~~~~~~~~
Error?: NULL
```

Pretty please advise - I really would like to solve this!
Would be very happy to help, if there is some way to. Am unfamiliar with Symfony or Silex though, so debugging would be a challenge.

**Comment by SamGoody** [comment]
Woops, I see that I posted to the wrong ticket - this was originally a thread for v1.2
Can this be moved? SHould I repost?

Thanks

**Comment by adobo** [comment]
@SamGoody perhaps the list (http://groups.google.com/group/agendav-general) is a better place for your issue, feel free to post!

@hamiltonian I'd suggest trying latest 2.0.0 beta. AgenDAV 2.0 uses sabre/vobject to parse iCalendar data, but AgenDAV 1.2.x uses a not-so-good iCalendar parser. As long as you don't need calendar sharing (Baïkal does not support ACL though) you will have a better experience with 2.0.

**Comment by yreveill** [comment]
Sorry to post here but I don't see the other ticket of SamGoody.
I have the same problem but with agendav-2.0.0-rc2 :/

So :
agendav-2.0.0-rc2 is ok with sabredav 3.1.x but 3.1.x no support shared calendars

agendav-2.0.0-rc2 is not ok with sabredav 3.2 which  support now shared calendars.

The error is : Received unexpected HTTP code 500 for input: Symfony\Component\HttpFoundation\ParameterBag

**Comment by adobo** [comment]
@yreveill would you mind to create a new issue? Thank you!

I'm closing this one, as @hamiltonian did not post any updates.
