### ISSUE TITLE
Error 400 when sharing calendar

### ISSUE THREAD

**Issue by Zhaobab** [adobo/agendav#185]
Hi !

I just tried to share a calendar to an mail address and I got an error 400, here is the logs:

[2016-11-08 14:31:09] agendav.WARNING: Received unexpected HTTP code 400 for input: Symfony\Component\HttpFoundation\ParameterBag::__set_state(array(    'parameters' =>    array (     '<SECRET_KEY>' => 'x15hjqITHFWwMp55KfirWeSow6lojXM6cyUapKbblpA',     'calendar' => '/baikal/cal.php/calendars/<USER_NAME>/default/',     'is_shared' => 'false',     'is_owned' => 'true',     'displayname' => 'Perso',     'calendar_color' => '#4caf50',     'filter' => '<EMAIL_ADRESS>',     'new_rw' => '0',   ), )) [] []

Any idea ?
Thank you!
Romain

**Comment by adobo** [comment]
Calendar sharing in AgenDAV is based on ACLs right now, and it is only fully tested on DAViCal.

Are there more log lines related to the error?

**Comment by Zhaobab** [comment]
No more lines

i use baikal as server for information, it was tested on it?

**Comment by fortitoo** [comment]
Hi !

First thanks for your great work on agendav 2, i love it !

I'm trying to use it on my own server running Debian Jessie / Nginx / PHP7 & Baikal 0.4.6 as cardDAV / calDAV server


I also have the same issue as Zhaobab when trying to share one of my calendars to another calDAV user but I don't think it's specific to calendar sharing, as I also have the same error when trying to change the color of one calendar and clicking the 'save' button.

here's the error log :
2016-11-09 10:07:08] agendav.WARNING: Received unexpected HTTP code 400 for input: Symfony\Component\HttpFoundation\ParameterBag::__set_state(array( 'parameters' => array ( 'lkjihgfedcba' => 'C5cLATrg9MHrQE6Ui3tbMzJY7tdru0f5Tn4ps9jps4k', 'calendar' => '/dav.php/calendars/myuser/default/', 'is_shared' => 'false', 'is_owned' => 'true', 'displayname' => 'Perso', 'calendar_color' => '#e91e63', ), )) [] []

So it look like it's more an issue with communication to baikal server.
I thought as your developpement environment VM uses baikal 0.4.6 it should run fine

do you need more logs to investigate on that ? settings.php ?

Thanks

**Comment by yreveill** [comment]
Hi,
from my own experience and documentation, Baikal 0.4.6 is based on sabre/dav 3.1.4 wich not fully support shared calendars.
Shared calendard are support with sabre/dav 3.2.0

You have to install sabre/dav 3.2.0, but at this point agendav-2.0.0-rc2 is bugged with sabre/dav 3.2.0 (Received unexpected HTTP code 500 for input: Symfony\Component\HttpFoundation\ParameterBag)

**Comment by fortitoo** [comment]
I just tried with sabre/dav 3.2 on baikal 0.4.6. baikal seems to run fine (can add new users / calendars)
but i can't login anymore on agendav with my user : displays authentication error, but nothing on logs...
when i switch back to sabre/dav 3.1.4 i can log again in agendav.


Anyway, back to the first issue, as I commented, the issue also occurs when trying to change the color of one of my calendars. It doesn't seems like a calendar sharing issue.
Is changing calendar colors supposed to work on rc2 ? 
I can help with debugging the issue if you need ...

thanks

**Comment by adobo** [comment]
@fortitoo, @yreveill, what happens if you disable calendar sharing, reload AgenDAV and try to change a calendar's color?

**Comment by fortitoo** [comment]
Hi, 
just tried disabling calendar sharing, and changing calendar's color is working now.

any update on sabre/dav 3.2 support with agendav ?

**Comment by yreveill** [comment]
Hello,

for me, with SabreDAV 3.2, with or without Agendav share settings on/off, I have :
 agendav-2.0.0/web/var/log/2016-11-22.log :

[2016-11-22 17:13:25] agendav.WARNING: Received unexpected HTTP code 500 (Server error: `REPORT https://webcal.<FDQN>.com/calendars/<user>@<FDQN>.com/default/` resulted in a `500 Internal Server Error` response: <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">   <s:sabredav-version>3 (truncated...) ) for input: Symfony\Component\HttpFoundation\ParameterBag::__set_state(array(    'parameters' =>    array (     'calendar' => '/calendars/<user>@<FDQN>.com/default/',     'start' => '2016-10-30',     'end' => '2016-12-11',     'timezone' => 'Europe/Madrid',     '_' => '1479831201035',   ), )) [] []

Agendav can write, but no read !

**Comment by yreveill** [comment]
Ok, problem seem to be REPORT with no body with digest authentification :

https://groups.google.com/forum/#!msg/agendav-general/5mbOEe7aZzQ/ONzT_TLbAQAJ

**Comment by yreveill** [comment]
Same problem :

curl \
--request REPORT \
--user <user>:<pass> \
--header "Content-Type: text/xml" \
--header "Depth:1" \
--data "<?xml version="1.0" encoding="UTF-8"?>\n<C:calendar-query xmlns:d="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:A="http://apple.com/ns/ical/"><d:prop><d:getetag/><C:calendar-data/></d:prop><C:filter><C:comp-filter name="VCALENDAR"><C:comp-filter name="VEVENT"><C:time-range start="20161029T220000Z" end="20161210T230000Z"/></C:comp-filter></C:comp-filter></C:filter></C:calendar-query>" \
https://<URL>/calendars/<user>/default/

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.0</s:sabredav-version>
  <s:exception>ErrorException</s:exception>
  <s:message>XMLReader::XML(): Empty string supplied as input</s:message>
</d:error>

**Comment by adobo** [comment]
@yreveill probably not related to sharing. Would you mind providing an HTTP debug log on a separate issue or via the mailing list?

Will work on WebDAV sharing without using ACL shares (#190).

**Comment by scramatte** [comment]
I'm  running sabre/dav 3.2  with Agendav 2.0  and sharing calendar doesn't works.
I still have 400 error. How can get complete xml trace  ?

**Comment by Rudloff** [comment]
It seems I'm having the same issue here: https://github.com/fruux/Baikal/issues/706

**Comment by adobo** [comment]
Last time I checked, sabre/dav ACL plugin had some little issues accepting AgenDAV issued ACLs. I can't recall what was exactly the problem.

Calendar sharing is a PITA on CalDAV. There seems not to be a clear standard (e.g. ACLs, multiple available drafts [[1]](https://evertpot.com/webdav-caldav-carddav-sharing/), [[2]](http://sabre.io/dav/caldav-sharing/)). It would be really great if AgenDAV could deal with more than one calendar sharing standard anytime in the future...
