### ISSUE TITLE
Add Support for Davical other readable calendars

### ISSUE THREAD

**Issue by Reigns95** [adobo/agendav#193]
I have the Problem that i can't see other readable calendars with a Davical Calendarserver. 
I*ve tested with Owncloud Calendarserver and there it works.
Please make it work for Davical"!

**Comment by adobo** [comment]
Could you elaborate, please? Is this related to #43?

**Comment by Reigns95** [comment]
Yes it is. Sry I didn't see that :/

**Comment by adobo** [comment]
Don't worry! I'm closing this one as duplicate of #43
