### ISSUE TITLE
Problem with Login and AgenDAV in Subdirectory on Nginx

### ISSUE THREAD

**Issue by Offerel** [adobo/agendav#196]
I would like to use AgenDAV 2 in a Subdirectory of my Nginx Installation. But if i call the Subdirectory, the URL is rewritten to subdirectory/login (and i get a 404 error), instead of subdirectory/index.php/login. My location directive looks like:

```
location /calendar {
		alias /var/www/agendav/web/public;
		index index.php;

		location ~ \.php$ {
			try_files $uri =404;
			fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include fastcgi_params;
		}
	}
```

**Comment by adobo** [comment]
Front controller on Silex (which AgenDAV is based on) doesn't expose its name (i.e. `index.php`), so the redirection URL looks right to me.

I would suggest following the nginx configuration guide linked at http://docs.agendav.org/en/stable/admin/installation/#other-web-servers . Looks like your configuration is missing some important parts.

I don't this is an AgenDAV issue, so please, feel free to post to the mailing list (https://groups.google.com/forum/#!forum/agendav-general) if you still have any issues after configuring nginx as the link above suggests.

Thank you!
