### ISSUE TITLE
Zimbra support patch

### ISSUE THREAD

**Issue by schlika** [adobo/agendav#35]
I just setup AgenDAV in front of a Zimbra (7) server. Works well now, but I had to manually patch

libs/davical/inc/caldav-client-v2.php : Zimbra sends "Allow: ..." answer on multiple lines, preg_replaces only gave the last line in $options_header in DoOptionsRequest(). AgenDAV could not get all properties and gave authentication error.

BTW, Zimbra Caldav urls are (add them to the doc) :

$config['caldav_principal_url'] = 'https://zimbra.server/dav/%u/';
$config['caldav_calendar_url'] = 'https://zimbra.server/dav/%s/';

patch :

*** adobo-agendav-d1870bb/libs/davical/inc/caldav-client-v2.php	Mon Jan 16 00:14:36 2012
--- agendav/libs/davical/inc/caldav-client-v2.php	Wed Jun  6 19:37:52 2012
***************
*** 352,356 ****
      $this->body = "";
      $headers = $this->DoRequest($url);
!     $options_header = preg_replace( '/^.*Allow: ([a-z, ]+)\r?\n.*/is', '$1', $headers );
      $options = array_flip( preg_split( '/[, ]+/', $options_header ));
      return $options;
--- 351,360 ----
      $this->body = "";
      $headers = $this->DoRequest($url);
!     $headers = str_replace("\r\n", "\n", $headers);
!     $ar_headers = explode("\n", $headers);
!     $options_header = "";
!     foreach ($ar_headers as $cur_headers) {
! 		$options_header .= preg_replace( '/^.*Allow: ([a-z, ]+)\r?\n.*/is', '$1', $cur_headers );
! 	}
      $options = array_flip( preg_split( '/[, ]+/', $options_header ));
      return $options;

Works well now. Sorry for lack of proper GITting I am in a hurry ....

**Comment by adobo** [comment]
Closing after 3 years of inactivity.
