### ISSUE TITLE
New created calenders are not fond due to case problems.

### ISSUE THREAD

**Issue by janLo** [adobo/agendav#65]
I have a user "Sany" in my davical installation. If she logs in using "Sany" the username on the upper right is "sany".

If she chates a new calendar there is no error, bit the new calendar is not in the list of calendars. If I cahange the username to "sany" (lowercase) in the server the new calendar appear in Sanys calendar list but every shared calendars from her to other users will no longer work for them (they are no longer in their lists).

**Comment by adobo** [comment]
Same as #111, which is marked as fixed for next release.
