### ISSUE TITLE
Configurable default view

### ISSUE THREAD

**Issue by vsessink** [adobo/agendav#72]
Currently, there is no configuration option to change the default view to "day" or "week". That poses somewhat of a problem in situations where someone has viewing rights on _all_ agenda's in an organisation: I've seen situations where 30+ agenda's are queried for the whole month - leading to a seemingly endless startup time after logging in.

It would be nice to be able to configure the default view as a configuration option, i.e. in the "config.php" file. Thus, a system operator could choose to setup the "day" view for everyone after logging in.

**Comment by adobo** [comment]
Next release will make configurable the default view.
