### ISSUE TITLE
"Apply lastest database schema" is not possible on initial setup.

### ISSUE THREAD

**Issue by DjSlash** [adobo/agendav#78]
In the installation guide:
> 1.3.3. Step 3: Apply latest database schema
> 
> Initial database structure created with *.sql files provides only a base structure for
> AgenDAV. It has to be modified to apply latest release changes. To do this, follow 
> instructions on Database upgrade.

Instrustions on database upgrade:
> Just use the provided bin/agendavcli script this way:
> ` $ ./bin/agendavcli dbupdate `

However, this will give you an error:
> The configuration file does not exist.

**Comment by adobo** [comment]
#115 is very similar to this one. I just marked it as fixed,, so I'm closing this one as well.
