### ISSUE TITLE
Database fails to connect if password has whitespace

### ISSUE THREAD

**Issue by jamer** [adobo/agendav#86]
CentOS 6.4
PostgreSQL 8.4.13
AgenDAV 1.2.6.2

AgenDAV fails to connect to the PostgreSQL database if the password has whitespace in it. When constructing the arguments to the pg_[p]connect() function at postgre_driver.php:70, the key is not escaped. Thus, whitespace is interpreted as a delimiter and cuts off the database password.

**Comment by adobo** [comment]
Current HEAD uses doctrine DBAL + ORM, so this should be fixed!
