### ISSUE TITLE
AgenDAV crashes when loading calendar that was updated using Outlook 2013 - using custom timezones, not supported by PHP

### ISSUE THREAD

**Issue by SimonSimCity** [adobo/agendav#88]
Hi, all

I newly created an instance of Baïkal and added this view on top of it.
After syncing some events in the calendar using Outlook 2013, I got a 500-error as response to the ajax-request fetching the calendar.

After enabling the development-mode, I got the following message:

Fatal error: Call to a member function getName() on a non-object in /srv/www/agendav/web/application/libraries/Icshelper.php on line 244

**Comment by SimonSimCity** [comment]
Has this issue been addressed as well by the finished implementation of #90?

**Comment by adobo** [comment]
Sure! Sabre/VObject seems not to have any issues with it. Tested on latest `HEAD`:
![captura de pantalla 2015-07-22 a las 20 03 05](https://cloud.githubusercontent.com/assets/776565/8833016/a5d34d52-30ac-11e5-9b56-1a30e61863c2.png)

**Comment by adobo** [comment]
Closing this as fixed
