### ISSUE TITLE
Add exception to recurring events

### ISSUE THREAD

**Issue by SimonSimCity** [adobo/agendav#98]
Hi,

Please implement the possibility to add an exception to recurring events. For example, we play football every Friday evening. If one week, we have some blocking event there, I don't want to stop the recurring event and create a new one starting next week - but I want to add an exception to the event-series.

Here's an example for full-day-events:
BEGIN:VEVENT
CREATED:20130913T134844Z
UID:7CD892DB-73C6-4384-B522-E23CB732C77C
DTSTART;VALUE=DATE:20130919
DTEND;VALUE=DATE:20130920
EXDATE;VALUE=DATE:20130926
RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=3
SUMMARY:Test
DTSTAMP:20130913T134934Z
SEQUENCE:7
END:VEVENT

Here's an example including day-time:
BEGIN:VEVENT
CREATED:20130913T135508Z
UID:800AA7C4-4EEE-4596-9F8A-D7DDA835C4B7
DTSTART;TZID=Europe/Berlin:20130919T100000
DTEND;TZID=Europe/Berlin:20130919T180000
EXDATE;TZID=Europe/Berlin:20130926T100000
RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=3
TRANSP:OPAQUE
SUMMARY:Test
DTSTAMP:20130913T135528Z
SEQUENCE:6
END:VEVENT

The extra entry here is:
EXDATE

**Comment by SimonSimCity** [comment]
@adobo that said - this issue is closed then?

**Comment by adobo** [comment]
Amost! Backend code is ready, but I'm right now working on the frontend (+ basic backend handling) to make AgenDAV able to add/remove exceptions.

**Comment by adobo** [comment]
Recurrence exceptions are supported by AgenDAV 2.0.0-beta1, so I'm closing this issue
